comment:
  image:
    repository: centhisone/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: centhisone/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: centhisone/ui
    tag: latest
  service:
    externalPort: 9292
