version: '3.3'
services:

  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
    - back_net

  ui:
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}/tcp
    networks:
    - front_net

  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
    - back_net
    - front_net

  comment:
    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
    - back_net
    - front_net

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
    - back_net
    - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
    - back_net

  mongo-exporter:
    image: percona/mongodb_exporter:0.20
    environment:
      MONGODB_URI: mongodb://post_db:27017
    networks:
    - back_net

  blackbox:
    image: ${USER_NAME}/blackbox
    ports:
      - '9115:9115'
    command:
      - --config.file=/config/blackbox.yml
    networks:
    - back_net
    - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
  back_net:
