---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-deployment
spec:
  replicas: 1
  selector:
    app: comment
  template:
    metadata:
      name: comment
      labels:
        app: comment
  spec:
    containers:
    - image: chromko/comment
      name: comment
